@Tag
Feature: Search Feature

Scenario Outline: Search for <search>
	Given Duckduckgo is open
	Given I search for <search>
	Given Search value should be <search>
	Then Perform Search
	Examples:
		| search |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |
		| browserstack |